// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.paka.sachy.model;

import cz.paka.sachy.model.Partie;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Partie_Roo_Configurable {
    
    declare @type: Partie: @Configurable;
    
}
